# Site settings
author: Smart Cai
url: http://cxjwin.github.com

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: objective_c
    css_class   : 'highlight'

theme: minima
plugins: [jekyll-paginate]

permalink: /:year/:month/:day/:title/

# Pagination Settings
paginate: 5
