# Site settings
author: Smart Cai
url: http://cxjwin.github.com

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: objective_c
    css_class   : 'highlight'

theme: minima
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
  
permalink: /:year/:month/:day/:title/

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
