highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title/
url: http://cxjwin.github.com
author: Smart Cai
safe: true
paginate: 16
# Gems
gems: [jekyll-paginate]